name: oss-app

services:
  oss-app:
    image: "mcr.microsoft.com/devcontainers/javascript-node:20-bullseye"
    command: tail -f /dev/null
    networks:
      - qfy
    ports:
      - "8080:3000"
    extra_hosts:
      - "minio.docker.internal:host-gateway"
    volumes:
      - ../..:/workspaces:cached
    depends_on:
      - minio
      - oss-app-redis

  minio:
    image: quay.io/minio/minio
    ports:
      - "9000:9000" # api 端口
      - "9001:9001" # 控制台端口
    environment:
      - MINIO_ROOT_USER=johndoe
      - MINIO_ROOT_PASSWORD=2Dp1pFT9ehMaoefpPLq9VuXqJg7Fc8g8
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped

  oss-app-redis:
    image: "redis:alpine"
    networks:
      - qfy
    ports:
      - "7379:6379"
    restart: unless-stopped
    volumes:
      - redis-data:/data

volumes:
  redis-data:
  minio-data:

networks:
  # The presence of these objects is sufficient to define them
  qfy:
    external: true
    name: qfy
